apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  selector:
    matchLabels:
      app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app
    spec:
      containers:
      - name: test
        image: ghcr.io/wade-srchae/app:dev.1234
        ports:
        - containerPort: 80