apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: test
          image: ghcr.io/wade-srchae/app:dev.20230323_1044
          imagePullPolicy: Always
          ports:
            - containerPort: 80
