apiVersion: apps/v1
kind: Deployment
metadata:
 name: user-api
spec:
 minReadySeconds: 10
 progressDeadlineSeconds: 180
 selector:
  matchLabels:
   app: user-api
 strategy:
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 0
  type: RollingUpdate
 template:
  metadata:
   name: user-api
   labels:
    app: user-api
  spec:
   containers: 
   - name: user-api
     image: user-api-image
     readinessProbe:
       periodSeconds: 1
       httpGet:
        path: /health
        port: 8080