apiVersion: v1
kind: Service
metadata:
  labels: test-deployment
  name: test-deployment
  namespace: default
spec:
  ports:
    - port: 9000 # 서비스가 사용할 포트
    targetPort: 9000 #서비스가 포워드할 컨테이너포트
    nodePort: 31212 # 서비스의 노드포트(적지않으면 30000~32768중 자동할당)
  type: NodePort

  selector:
  app: app # app=MyHelloworld인 모든 pod는 이 서비스에 속한다.