apiVersion: v1
kind: Service
metadata:
  labels: test-deployment
  name: test-deployment
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9000 # 서비스가 사용할 포트
      targetPort: 9000 #서비스가 포워드할 컨테이너포트
  selector:
    app: app # app=MyHelloworld인 모든 pod는 이 서비스에 속한다.